# Generated by Django 2.2.16 on 2022-11-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221102_1246'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cannot_follow_yourself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
